# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmonitor.proto\x12\x07monitor\"\x1e\n\x0bPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0cPingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\x06Metric\x12\x11\n\tcapacidad\x18\x01 \x01(\x02\"\x13\n\x11GetMetricsRequest\"6\n\x12GetMetricsResponse\x12 \n\x07metrics\x18\x01 \x03(\x0b\x32\x0f.monitor.Metric\"&\n\x0fRegisterRequest\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\"$\n\x10RegisterResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"(\n\x11UnregisterRequest\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\"&\n\x12UnregisterResponse\x12\x10\n\x08response\x18\x01 \x01(\t2\x95\x02\n\x07Monitor\x12\x35\n\x04Ping\x12\x14.monitor.PingRequest\x1a\x15.monitor.PingResponse\"\x00\x12G\n\nGetMetrics\x12\x1a.monitor.GetMetricsRequest\x1a\x1b.monitor.GetMetricsResponse\"\x00\x12\x41\n\x08Register\x12\x18.monitor.RegisterRequest\x1a\x19.monitor.RegisterResponse\"\x00\x12G\n\nUnregister\x12\x1a.monitor.UnregisterRequest\x1a\x1b.monitor.UnregisterResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'monitor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PINGREQUEST._serialized_start=26
  _PINGREQUEST._serialized_end=56
  _PINGRESPONSE._serialized_start=58
  _PINGRESPONSE._serialized_end=89
  _METRIC._serialized_start=91
  _METRIC._serialized_end=118
  _GETMETRICSREQUEST._serialized_start=120
  _GETMETRICSREQUEST._serialized_end=139
  _GETMETRICSRESPONSE._serialized_start=141
  _GETMETRICSRESPONSE._serialized_end=195
  _REGISTERREQUEST._serialized_start=197
  _REGISTERREQUEST._serialized_end=235
  _REGISTERRESPONSE._serialized_start=237
  _REGISTERRESPONSE._serialized_end=273
  _UNREGISTERREQUEST._serialized_start=275
  _UNREGISTERREQUEST._serialized_end=315
  _UNREGISTERRESPONSE._serialized_start=317
  _UNREGISTERRESPONSE._serialized_end=355
  _MONITOR._serialized_start=358
  _MONITOR._serialized_end=635
# @@protoc_insertion_point(module_scope)
